name: Frontend

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # Setup node
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install npx
      run: npm install -g npx

    - name: Install dependencies
      working-directory: server
      run: npm install
    
    - name: Run linting
      working-directory: server
      run: npm run lint
      env:
        ENV: ci

    - name: Run unit tests
      working-direcotry: server
      run: npm test
      env:
        ENV: ci
