name: Server

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Setup node
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install dependencies
      working-directory: server
      run: npm install
    
    - name: Run linting
      working-directory: server
      run: npm run lint
      env:
        ENV: ci

    - name: Run unit tests
      working-directory: server
      run: npm test
      env:
        ENV: ci
